/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.CareTeamOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CareTeamLeaderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class RaiseARequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RaiseARequestJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;

    private String message;
    private int numberOfStaffMembers;
    private Date fromOperationDate;
    private Date toOperationDate;
    private String patientName;
    private String operation;
    private int count = 0;
    private String errorMessage;

    public RaiseARequestJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplierAdminWorkArea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMessage = new javax.swing.JTextArea();
        lblOperationInfo = new javax.swing.JLabel();
        lblNumberOfStaffMembers = new javax.swing.JLabel();
        spnStaff = new javax.swing.JSpinner();
        lblDate = new javax.swing.JLabel();
        jDCFromOperationDate = new com.toedter.calendar.JDateChooser();
        btnSend = new javax.swing.JButton();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        jDCToOperationDate = new com.toedter.calendar.JDateChooser();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOperation = new javax.swing.JTextField();

        lblSupplierAdminWorkArea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSupplierAdminWorkArea.setForeground(new java.awt.Color(102, 204, 255));
        lblSupplierAdminWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplierAdminWorkArea.setText("Raise A Request");

        txtAreaMessage.setColumns(20);
        txtAreaMessage.setRows(5);
        jScrollPane1.setViewportView(txtAreaMessage);

        lblOperationInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOperationInfo.setText("Operation Info");

        lblNumberOfStaffMembers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumberOfStaffMembers.setText("Number of Staff Members");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate.setText("Date");

        btnSend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblFrom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFrom.setText("From");

        lblTo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTo.setText("To");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Patient Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Operation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblSupplierAdminWorkArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTo)
                            .addComponent(lblNumberOfStaffMembers)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDate)
                                .addGap(22, 22, 22)
                                .addComponent(lblFrom)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDCFromOperationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDCToOperationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblOperationInfo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblSupplierAdminWorkArea)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOperationInfo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfStaffMembers)
                    .addComponent(spnStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDate)
                        .addComponent(lblFrom))
                    .addComponent(jDCFromOperationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTo)
                    .addComponent(jDCToOperationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSend)
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        errorMessage = "";
        count = 0;

        message = txtAreaMessage.getText().trim();
        patientName = txtPatientName.getText().trim();
        operation = txtOperation.getText().trim();
        fromOperationDate = (Date) jDCFromOperationDate.getDate();
        toOperationDate = (Date) jDCToOperationDate.getDate();
        numberOfStaffMembers = (int) spnStaff.getValue();

        if (message.isEmpty() || fromOperationDate == null || toOperationDate == null || patientName.isEmpty() || operation.isEmpty()) {
            errorMessage += "You have left the below mentioned field as blank, Please fill them.\n";

            if (message.isEmpty()) {
                count++;
                errorMessage += count + ". Operation Info.\n";
            }
            if (fromOperationDate == null) {
                count++;
                errorMessage += count + ". From Operation Date.\n";
            }
            if (toOperationDate == null) {
                count++;
                errorMessage += count + ". To Operation Date.\n";
            }
            if (patientName.isEmpty()) {
                count++;
                errorMessage += count + ". Patient Name.\n";
            }
            if (operation.isEmpty()) {
                count++;
                errorMessage += count + ". Operation.\n";
            }
        }

        if (!patientName.matches("[a-zA-Z]+")) {
            count++;
            errorMessage += "Invalid Character in Patient Name, Patient Name can accept only alphabets\n";
        }

        if (!operation.matches("[a-zA-Z]+")) {
            count++;
            errorMessage += "Invalid Character in Operation Name, Operation Name can accept only alphabets\n";
        }

        if (!txtAreaMessage.getText().trim().matches("[a-zA-Z0-9 ]+")) {
            count++;
            errorMessage += "Text Area can contain only character, number and spaces.\n";
        }

        if (numberOfStaffMembers < 1) {
            count++;
            errorMessage += "Number of staff members must be greater than zero";
        }
        if (toOperationDate.before(fromOperationDate)) {
            count++;
            errorMessage += "To OPeration Date cant be less than FromOperation date.\n";
        }
        if (toOperationDate.before(new Date())) {
            count++;
            errorMessage += "To Operation Date cannot be less than Current Date.\n";
        }
        if (fromOperationDate.before(new Date())) {
            count++;
            errorMessage += "From Operation Date cannot be less than Current Date.\n";
        }

        if (count == 0) {
            CareTeamLeaderWorkRequest careTeamLeaderWorkRequest = new CareTeamLeaderWorkRequest();
            careTeamLeaderWorkRequest.setMessage(message);
            careTeamLeaderWorkRequest.setFromOperationDate(fromOperationDate);
            careTeamLeaderWorkRequest.setToOperationDate(toOperationDate);
            careTeamLeaderWorkRequest.setNumberOfStaffMembers(numberOfStaffMembers);
            careTeamLeaderWorkRequest.setStatus(WorkRequest.TypeOfStatus.Pending.getValue());
            careTeamLeaderWorkRequest.setDoctor(userAccount);
            careTeamLeaderWorkRequest.setRequestDate(new Date());
            careTeamLeaderWorkRequest.setPatientName(patientName);
            careTeamLeaderWorkRequest.setOperation(operation);

            userAccount.getWorkQueue().getWorkRequestList().add(careTeamLeaderWorkRequest);

            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof CareTeamOrganization) {
                    organization.getWorkQueue().getWorkRequestList().add(careTeamLeaderWorkRequest);
                }
            }

            JOptionPane.showMessageDialog(null, "Request has been raised successfully");
        } else {
            JOptionPane.showMessageDialog(null, errorMessage);
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private com.toedter.calendar.JDateChooser jDCFromOperationDate;
    private com.toedter.calendar.JDateChooser jDCToOperationDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblNumberOfStaffMembers;
    private javax.swing.JLabel lblOperationInfo;
    private javax.swing.JLabel lblSupplierAdminWorkArea;
    private javax.swing.JLabel lblTo;
    private javax.swing.JSpinner spnStaff;
    private javax.swing.JTextArea txtAreaMessage;
    private javax.swing.JTextField txtOperation;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
