/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierEnterpriseAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import UserInterface.SignUpPersonDetailJDialog;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class ManageOrganizationAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationAdminJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private Organization organization;
    private ArrayList<Person> personDirectory;
    private ArrayList<UserAccount> userAccountDirectory;

    public ManageOrganizationAdminJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;

        populateOrganizationAdminTable();
        populateOrganizationComboBox();
    }

    private void populateOrganizationAdminTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblOrganizationAdmin.getModel();
        defaultTableModel.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountList()) {
                Object[] row = new Object[4];
                row[0] = enterprise.getOrganizationName();
                row[1] = organization.getOrganizationName();
                row[2] = organization.getSupportedRole();
                row[3] = userAccount.getUserName();

                defaultTableModel.addRow(row);
            }
        }
    }

    private void populateOrganizationComboBox() {
        cmbOrganization.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            cmbOrganization.addItem(organization);
        }
    }

    private void populateRoleComboBox(Organization organization) {
        cmbRole.removeAllItems();;

        for (Role role : organization.getSupportedRole()) {
            cmbRole.addItem(role);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizationAdmin = new javax.swing.JTable();
        lblOrganizationAdmin = new javax.swing.JLabel();
        lblNewOrganizationAdmin = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        btnAdminDetail = new javax.swing.JButton();
        cmbOrganization = new javax.swing.JComboBox();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        tblOrganizationAdmin.setBackground(new java.awt.Color(255, 153, 0));
        tblOrganizationAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblOrganizationAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Organization Name", "Role", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganizationAdmin);
        if (tblOrganizationAdmin.getColumnModel().getColumnCount() > 0) {
            tblOrganizationAdmin.getColumnModel().getColumn(0).setResizable(false);
            tblOrganizationAdmin.getColumnModel().getColumn(1).setResizable(false);
            tblOrganizationAdmin.getColumnModel().getColumn(2).setResizable(false);
            tblOrganizationAdmin.getColumnModel().getColumn(3).setResizable(false);
        }

        lblOrganizationAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrganizationAdmin.setForeground(new java.awt.Color(102, 204, 255));
        lblOrganizationAdmin.setText("Organization Admin's");

        lblNewOrganizationAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNewOrganizationAdmin.setForeground(new java.awt.Color(102, 204, 255));
        lblNewOrganizationAdmin.setText("Create New Organization Admin");

        lblOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrganization.setText("Organization");

        btnAdminDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdminDetail.setText("Click here to enter Admin Details");
        btnAdminDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDetailActionPerformed(evt);
            }
        });

        cmbOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationActionPerformed(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRole.setText("Role");

        cmbRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrganizationAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRole)
                            .addComponent(lblOrganization))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbOrganization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNewOrganizationAdmin)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdminDetail)
                        .addGap(36, 36, 36)))
                .addGap(342, 342, 342))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganizationAdmin)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblNewOrganizationAdmin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdminDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDetailActionPerformed
        Organization organization = (Organization) cmbOrganization.getSelectedItem();
        personDirectory = organization.getPersonDirectory().getPersonList();
        userAccountDirectory = organization.getUserAccountDirectory().getUserAccountList();
        //organization = enterprise;
        Role role = (Role) cmbRole.getSelectedItem();
        if (organization != null && role != null) {
                JFrame frame = new JFrame();
                SignUpPersonDetailJDialog supdjd = new SignUpPersonDetailJDialog(frame, true, organization, ecoSystem, personDirectory, userAccountDirectory);
                supdjd.setVisible(true);
           
            populateOrganizationAdminTable();
            populateOrganizationComboBox();
        } else {
            JOptionPane.showMessageDialog(null, "Please select all combo boxes");
        }
    }//GEN-LAST:event_btnAdminDetailActionPerformed

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
        cmbRole.removeAllItems();

        Organization organization = (Organization) cmbOrganization.getSelectedItem();
        if (organization != null) {
            populateRoleComboBox(organization);
        }
//        Enterprise enterprise = (Enterprise) cmbOrganization.getSelectedItem();
//        if (enterprise != null) {
//            for (Role role : enterprise.getSupportedRole()) {
//                cmbRole.addItem(role);
//            }
//        }
    }//GEN-LAST:event_cmbOrganizationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateOrganizationAdminTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminDetail;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cmbOrganization;
    private javax.swing.JComboBox cmbRole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNewOrganizationAdmin;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblOrganizationAdmin;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTable tblOrganizationAdmin;
    // End of variables declaration//GEN-END:variables
}
