/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierWorkArea;

import Business.EcoSystem;
import Business.Person.Supplier;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SupplierWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class ManageEnrollmentStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnrollmentStatusJPanel
     */
    private JPanel userProcessContainer;
    private Supplier supplier;
    private UserAccount userAccount;
    private EcoSystem ecoSystem = EcoSystem.getInstance();
    public ManageEnrollmentStatusJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplier = (Supplier)userAccount.getPerson();
        this.userAccount = userAccount;
        
        if(supplier.getIsEnrolled().equals("YES")){
            txtEnrollmentStatus.setText("Supplier is Enrolled");
        }
        else{
            txtEnrollmentStatus.setText("Supplier is Not Enrolled");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplier = new javax.swing.JLabel();
        lblEnrollmentStatus = new javax.swing.JLabel();
        txtEnrollmentStatus = new javax.swing.JTextField();
        btnSendEnrollmentRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(102, 204, 255));
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplier.setText("Manage Enrollment Status");

        lblEnrollmentStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnrollmentStatus.setForeground(new java.awt.Color(102, 204, 255));
        lblEnrollmentStatus.setText("Enrollment Status");

        btnSendEnrollmentRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSendEnrollmentRequest.setText("Send Enrollment Request");
        btnSendEnrollmentRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEnrollmentRequestActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(lblEnrollmentStatus)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnrollmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(327, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSupplier)
                        .addGap(369, 369, 369))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSendEnrollmentRequest)
                        .addGap(387, 387, 387))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblSupplier)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnrollmentStatus)
                    .addComponent(txtEnrollmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnSendEnrollmentRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendEnrollmentRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEnrollmentRequestActionPerformed
        
        
        if(supplier.getIsEnrolled().equals("NO")){
            SupplierWorkRequest supplierWorkRequest = new SupplierWorkRequest();
            supplierWorkRequest.setStatus(WorkRequest.TypeOfStatus.Pending.getValue());
            supplierWorkRequest.setSupplier(userAccount);
            supplierWorkRequest.setRequestDate(new Date());
            supplierWorkRequest.setMessage("Please Enroll me in the Organization");
            
            userAccount.getWorkQueue().getWorkRequestList().add(supplierWorkRequest);
            ecoSystem.getWorkQueue().getWorkRequestList().add(supplierWorkRequest);
        }
        else{
            JOptionPane.showMessageDialog(null, "The Supplier is already Enrolled");
        }
    }//GEN-LAST:event_btnSendEnrollmentRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendEnrollmentRequest;
    private javax.swing.JLabel lblEnrollmentStatus;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JTextField txtEnrollmentStatus;
    // End of variables declaration//GEN-END:variables
}
