/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierWorkArea;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplierWorkArea = new javax.swing.JLabel();
        btnSendEnrollmentRequest = new javax.swing.JButton();
        btnManageProductCatalog = new javax.swing.JButton();

        lblSupplierWorkArea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSupplierWorkArea.setForeground(new java.awt.Color(102, 204, 255));
        lblSupplierWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplierWorkArea.setText("Supplier Work Area");

        btnSendEnrollmentRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSendEnrollmentRequest.setText("Send/Check Enrollment Request");
        btnSendEnrollmentRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEnrollmentRequestActionPerformed(evt);
            }
        });

        btnManageProductCatalog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageProductCatalog.setText("Manage Product Catalog >>");
        btnManageProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductCatalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSupplierWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSendEnrollmentRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(btnManageProductCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(366, 366, 366))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblSupplierWorkArea)
                .addGap(43, 43, 43)
                .addComponent(btnSendEnrollmentRequest)
                .addGap(26, 26, 26)
                .addComponent(btnManageProductCatalog)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductCatalogActionPerformed
        ManageDeviceCatalogJPanel mpcjp = new ManageDeviceCatalogJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("Manage Product Catalog JPanel",mpcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageProductCatalogActionPerformed

    private void btnSendEnrollmentRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEnrollmentRequestActionPerformed
        ManageEnrollmentStatusJPanel mesjp = new ManageEnrollmentStatusJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("Manage Enrollment Status JPanel",mesjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSendEnrollmentRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProductCatalog;
    private javax.swing.JButton btnSendEnrollmentRequest;
    private javax.swing.JLabel lblSupplierWorkArea;
    // End of variables declaration//GEN-END:variables
}
