/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.WareHouseEnterpriseAdminWorkArea;

import Business.Device;
import Business.Enterprise.Enterprise;
import Business.Enterprise.WareHouseEnterprise;
import Business.Schedule;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class IndividualDeviceBookingHistoryJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DeviceBookingHistoryJDialog
     */
    private JFrame frame;
    private Enterprise enterprise;
    private Device selectedDevice;
    private int count;
    private WareHouseEnterprise wareHouseEnterprise;
    public IndividualDeviceBookingHistoryJDialog(JFrame frame, boolean modal, WareHouseEnterprise wareHouseEnterprise, Device dev, int count) {
        super(frame, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.wareHouseEnterprise = wareHouseEnterprise;
        selectedDevice = dev;
        this.count = count;
        populateDeviceHistory();
        
    }

    private void populateDeviceHistory(){
        DefaultTableModel defaultTableModel = (DefaultTableModel)tblDeviceHistory.getModel();
        defaultTableModel.setRowCount(0);
        
        for(Schedule schedule : wareHouseEnterprise.getScheduleList().getScheduleCatalog()){
            Device dev = schedule.getDevice();
            if(selectedDevice.getUniqueDeviceIdentifier().equalsIgnoreCase(dev.getUniqueDeviceIdentifier())){
                Object[] row = new Object[4];
                
                row[0] = dev;
                row[1] = dev.getUniqueDeviceIdentifier();
                row[2] = schedule.getEnterprise();
                row[3] = schedule.getDate();
                
                defaultTableModel.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeviceHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeviceHistory = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDeviceHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDeviceHistory.setForeground(new java.awt.Color(102, 204, 255));
        lblDeviceHistory.setText("Device History");

        tblDeviceHistory.setBackground(new java.awt.Color(255, 153, 0));
        tblDeviceHistory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDeviceHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device Name", "Unique DeviceID", "Hospital Name", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblDeviceHistory);

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(lblDeviceHistory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(555, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(539, 539, 539))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblDeviceHistory)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnOK)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualDeviceBookingHistoryJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualDeviceBookingHistoryJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualDeviceBookingHistoryJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualDeviceBookingHistoryJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IndividualDeviceBookingHistoryJDialog dialog = new IndividualDeviceBookingHistoryJDialog(new javax.swing.JFrame(), true, wareHouseEnterprise, selectedDevice, count);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeviceHistory;
    private javax.swing.JTable tblDeviceHistory;
    // End of variables declaration//GEN-END:variables
}
