/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.WareHouseEnterpriseAdminWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.AccountOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Organization.SalesOrganization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class ManageWHOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageWHOrganizationJPanel
     */
    private JPanel userProcessConatiner;
    private Enterprise enterprise;
    
    public ManageWHOrganizationJPanel(JPanel userProcessConatiner, Enterprise enterprise) {
        initComponents();
        this.userProcessConatiner = userProcessConatiner;
        this.enterprise = enterprise;
        
        populateOrganizationTable();
        populateOrganizationTypeComboBox();
    }

    private void populateOrganizationTable(){
        DefaultTableModel defaultTableModel = (DefaultTableModel)tblOrganizationName.getModel();
        defaultTableModel.setRowCount(0);
        
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            Object[] row = new Object[2];
            if(organization instanceof InventoryOrganization){
                InventoryOrganization inventoryOrganization = (InventoryOrganization)organization;
                row[0] = inventoryOrganization.getOrganizationID();
            }
            if(organization instanceof AccountOrganization){
                AccountOrganization accountOrganization = (AccountOrganization)organization;
                row[0] = accountOrganization.getOrganizationID();
            }
            row[1] = organization.getOrganizationName();
            
            defaultTableModel.addRow(row);
        }
    }
    
    private void populateOrganizationTypeComboBox(){
        cmbOrganizationType.removeAllItems();;
        
        for(Organization.OrganizationType type : Organization.OrganizationType.values()){
            if(type.getValue().equals(Organization.OrganizationType.Inventory.getValue()) || type.getValue().equals(Organization.OrganizationType.Account.getValue())){
                cmbOrganizationType.addItem(type);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrganizationType = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizationName = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnCreateOrganization = new javax.swing.JButton();
        cmbOrganizationType = new javax.swing.JComboBox();
        btnRefresh = new javax.swing.JButton();
        lblNewOrganization = new javax.swing.JLabel();

        lblOrganizationType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrganizationType.setText("Organization Type");

        lblOrganization.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrganization.setForeground(new java.awt.Color(102, 204, 255));
        lblOrganization.setText("Organization's");

        tblOrganizationName.setBackground(new java.awt.Color(255, 153, 0));
        tblOrganizationName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblOrganizationName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganizationName);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreateOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreateOrganization.setText("Create Organization");
        btnCreateOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrganizationActionPerformed(evt);
            }
        });

        cmbOrganizationType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbOrganizationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblNewOrganization.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNewOrganization.setForeground(new java.awt.Color(102, 204, 255));
        lblNewOrganization.setText("Create New Organization");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrganization)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBack)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(lblNewOrganization))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(btnCreateOrganization))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(lblOrganizationType)
                        .addGap(18, 18, 18)
                        .addComponent(cmbOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(lblOrganization))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNewOrganization)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganizationType)
                    .addComponent(cmbOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnCreateOrganization)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrganizationActionPerformed
        
        int count = 0;
        Organization.OrganizationType type = (Organization.OrganizationType)cmbOrganizationType.getSelectedItem();
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if(organization.getOrganizationName().equals(type.getValue())){
                count++;
            }
        }
        if(count == 0){
            enterprise.getOrganizationDirectory().createOrganization(type);
        }
        else{
            JOptionPane.showMessageDialog(null, "The selected organization is already created");
        }
        populateOrganizationTable();
    }//GEN-LAST:event_btnCreateOrganizationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessConatiner.remove(this);
        CardLayout layout = (CardLayout)userProcessConatiner.getLayout();
        layout.previous(userProcessConatiner);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateOrganizationTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateOrganization;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cmbOrganizationType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNewOrganization;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblOrganizationType;
    private javax.swing.JTable tblOrganizationName;
    // End of variables declaration//GEN-END:variables
}
