/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WareHouseEnterpriseAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class WareHouseEnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WareHouseEnterpriseWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;

    public WareHouseEnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplierAdminWorkArea = new javax.swing.JLabel();
        btnManageOrganization = new javax.swing.JButton();
        btnManageOrganizationAdmin = new javax.swing.JButton();
        btnViewDeviceDetailsJPanel = new javax.swing.JButton();

        lblSupplierAdminWorkArea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSupplierAdminWorkArea.setForeground(new java.awt.Color(102, 204, 255));
        lblSupplierAdminWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplierAdminWorkArea.setText("WareHouse Enterprise Admin Work Area");

        btnManageOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageOrganization.setText("Manage Organization");
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });

        btnManageOrganizationAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageOrganizationAdmin.setText("Manage Organization Admin");
        btnManageOrganizationAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationAdminActionPerformed(evt);
            }
        });

        btnViewDeviceDetailsJPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewDeviceDetailsJPanel.setText("View Device Details");
        btnViewDeviceDetailsJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeviceDetailsJPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierAdminWorkArea)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageOrganizationAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewDeviceDetailsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(lblSupplierAdminWorkArea)
                .addGap(37, 37, 37)
                .addComponent(btnManageOrganization)
                .addGap(33, 33, 33)
                .addComponent(btnManageOrganizationAdmin)
                .addGap(32, 32, 32)
                .addComponent(btnViewDeviceDetailsJPanel)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed
        ManageWHOrganizationJPanel mwhojp = new ManageWHOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("Manage WH Organization JPanel", mwhojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrganizationActionPerformed

    private void btnManageOrganizationAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationAdminActionPerformed
        ManageWHOrganizationAdminJPanel mwhoajp = new ManageWHOrganizationAdminJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("Manage WH Organization Admin JPanel", mwhoajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageOrganizationAdminActionPerformed

    private void btnViewDeviceDetailsJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeviceDetailsJPanelActionPerformed
        ViewWHDeviceDetailJPanel vwhddjp = new ViewWHDeviceDetailJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("View WH Device Detail JPanel", vwhddjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDeviceDetailsJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnManageOrganizationAdmin;
    private javax.swing.JButton btnViewDeviceDetailsJPanel;
    private javax.swing.JLabel lblSupplierAdminWorkArea;
    // End of variables declaration//GEN-END:variables
}
