/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CareTeamSpecialistWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Person.Doctor;
import Business.Person.Person;
import Business.Person.Staff;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class CareTeamSpecialistWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CareTeamSpecialistWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;

    public CareTeamSpecialistWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCareTeamSpecialistWorkArea = new javax.swing.JLabel();
        btnViewBookingDetails = new javax.swing.JButton();

        lblCareTeamSpecialistWorkArea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCareTeamSpecialistWorkArea.setForeground(new java.awt.Color(102, 204, 255));
        lblCareTeamSpecialistWorkArea.setText("Care Team Specialist Work Area");

        btnViewBookingDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewBookingDetails.setText("View Booking Details");
        btnViewBookingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookingDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCareTeamSpecialistWorkArea)
                        .addGap(351, 351, 351))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnViewBookingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(372, 372, 372))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblCareTeamSpecialistWorkArea)
                .addGap(117, 117, 117)
                .addComponent(btnViewBookingDetails)
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBookingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookingDetailsActionPerformed
        ViewBookingDetailsJPanel vbrjp = new ViewBookingDetailsJPanel(userProcessContainer,userAccount, organization, enterprise, ecoSystem);
        userProcessContainer.add("New Booking Request JPanel", vbrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewBookingDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewBookingDetails;
    private javax.swing.JLabel lblCareTeamSpecialistWorkArea;
    // End of variables declaration//GEN-END:variables
}
