/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CareTeamSpecialistWorkArea;

import Business.WorkQueue.CareTeamLeaderWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class OldBookingRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OldBookingRequestJPanel
     */
    
    private JPanel userProcessConatiner;
    private CareTeamLeaderWorkRequest workRequest;
    
    public OldBookingRequestJPanel(JPanel userProcessConatiner, CareTeamLeaderWorkRequest workRequest) {
        initComponents();
        
        this.userProcessConatiner = userProcessConatiner;
        this.workRequest = workRequest;
        
        populateFields();
    }
    
    private void populateFields(){
        txtDoctor.setText(workRequest.getDoctor().getPerson().getFirstName() + " " + workRequest.getDoctor().getPerson().getLastName());
        txtOperation.setText(workRequest.getOperation());
        txtPatientName.setText(workRequest.getPatientName());
        txtOperationDate.setText(workRequest.getOperationDate());
        txtRoomNumber.setText(String.valueOf(workRequest.getRoomNumber()));
        txtResult.setText(workRequest.getTestResults());
        txtMessage.setText(workRequest.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRequestDetail = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        lblOperation = new javax.swing.JLabel();
        lblOperationDate = new javax.swing.JLabel();
        lblRoomNumber = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblResults = new javax.swing.JLabel();
        txtDoctor = new javax.swing.JTextField();
        txtOperation = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtOperationDate = new javax.swing.JTextField();
        txtRoomNumber = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        lblRequestDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRequestDetail.setForeground(new java.awt.Color(102, 204, 255));
        lblRequestDetail.setText("Request Detail");

        lblDoctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDoctor.setText("Doctor :");

        lblOperation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOperation.setText("Operation :");

        lblOperationDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOperationDate.setText("Operation Date :");

        lblRoomNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRoomNumber.setText("Room Number :");

        lblPatientName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPatientName.setText("Patient Name :");

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMessage.setText("Message :");

        lblResults.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResults.setText("Results :");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRequestDetail)
                .addGap(429, 429, 429))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOperation)
                            .addComponent(lblDoctor)
                            .addComponent(lblPatientName)
                            .addComponent(lblOperationDate)
                            .addComponent(lblRoomNumber)
                            .addComponent(lblResults)
                            .addComponent(lblMessage))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMessage)
                            .addComponent(txtResult)
                            .addComponent(txtRoomNumber)
                            .addComponent(txtOperationDate)
                            .addComponent(txtPatientName)
                            .addComponent(txtOperation)
                            .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnBack)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblRequestDetail)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctor)
                    .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperation)
                    .addComponent(txtOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperationDate)
                    .addComponent(txtOperationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomNumber)
                    .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResults)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnBack)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessConatiner.remove(this);
        CardLayout layout = (CardLayout)userProcessConatiner.getLayout();
        layout.previous(userProcessConatiner);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOperation;
    private javax.swing.JLabel lblOperationDate;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRequestDetail;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblRoomNumber;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtOperation;
    private javax.swing.JTextField txtOperationDate;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtRoomNumber;
    // End of variables declaration//GEN-END:variables
}
