/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CareTeamSpecialistWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CareTeamLeaderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class ViewBookingDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBookingDetailsJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private CareTeamLeaderWorkRequest careTeamLeaderWorkRequest;

    public ViewBookingDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;

        populatePendingWorkRequest();
        populateWorkRequestHistoryTable();
    }

    private void populatePendingWorkRequest() {

        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPendingWorkRequest.getModel();
        defaultTableModel.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            careTeamLeaderWorkRequest = (CareTeamLeaderWorkRequest) request;

            if (careTeamLeaderWorkRequest.getStatus().equalsIgnoreCase(WorkRequest.TypeOfStatus.Pending.getValue())) {
                Object[] row = new Object[4];

                row[0] = careTeamLeaderWorkRequest;
                row[1] = careTeamLeaderWorkRequest.getDoctor().getPerson().getFirstName();
                row[2] = careTeamLeaderWorkRequest.getRequestDate();
                row[3] = careTeamLeaderWorkRequest.getStatus();

                defaultTableModel.addRow(row);
            }

        }
    }

    private void populateWorkRequestHistoryTable() {

        DefaultTableModel defaultTableModel = (DefaultTableModel) tblWorkRequestHistory.getModel();
        defaultTableModel.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            careTeamLeaderWorkRequest = (CareTeamLeaderWorkRequest) request;

            if (careTeamLeaderWorkRequest.getStatus().equalsIgnoreCase(WorkRequest.TypeOfStatus.Completed.getValue())) {
                Object[] row = new Object[4];

                row[0] = careTeamLeaderWorkRequest;
                row[1] = careTeamLeaderWorkRequest.getDoctor().getPerson().getFirstName();
                row[2] = careTeamLeaderWorkRequest.getRequestDate();
                row[3] = careTeamLeaderWorkRequest.getStatus();

                defaultTableModel.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpRequestHistory = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendingWorkRequest = new javax.swing.JTable();
        lblOrganizationsPendingWorkRequest = new javax.swing.JLabel();
        btnViewDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblOrganizationsWorkRequestHistory = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWorkRequestHistory = new javax.swing.JTable();
        btnViewRequestDetail = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        tblPendingWorkRequest.setBackground(new java.awt.Color(255, 153, 0));
        tblPendingWorkRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblPendingWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Doctor", "Request Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPendingWorkRequest);
        if (tblPendingWorkRequest.getColumnModel().getColumnCount() > 0) {
            tblPendingWorkRequest.getColumnModel().getColumn(0).setResizable(false);
            tblPendingWorkRequest.getColumnModel().getColumn(1).setResizable(false);
            tblPendingWorkRequest.getColumnModel().getColumn(2).setResizable(false);
            tblPendingWorkRequest.getColumnModel().getColumn(3).setResizable(false);
        }

        lblOrganizationsPendingWorkRequest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrganizationsPendingWorkRequest.setForeground(new java.awt.Color(102, 204, 255));
        lblOrganizationsPendingWorkRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrganizationsPendingWorkRequest.setText("Organization's Pending Work Request");

        btnViewDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewDetail.setText("View Detail");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnViewDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblOrganizationsPendingWorkRequest)))
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblOrganizationsPendingWorkRequest)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnViewDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(86, 86, 86))
        );

        tbpRequestHistory.addTab("Pending Work Request", jPanel1);

        lblOrganizationsWorkRequestHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrganizationsWorkRequestHistory.setForeground(new java.awt.Color(102, 204, 255));
        lblOrganizationsWorkRequestHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrganizationsWorkRequestHistory.setText("Organization's Work Request History");

        tblWorkRequestHistory.setBackground(new java.awt.Color(255, 153, 0));
        tblWorkRequestHistory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblWorkRequestHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Doctor", "Resolve Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblWorkRequestHistory);
        if (tblWorkRequestHistory.getColumnModel().getColumnCount() > 0) {
            tblWorkRequestHistory.getColumnModel().getColumn(0).setResizable(false);
            tblWorkRequestHistory.getColumnModel().getColumn(1).setResizable(false);
            tblWorkRequestHistory.getColumnModel().getColumn(2).setResizable(false);
            tblWorkRequestHistory.getColumnModel().getColumn(3).setResizable(false);
        }

        btnViewRequestDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewRequestDetail.setText("View Detail");
        btnViewRequestDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestDetailActionPerformed(evt);
            }
        });

        btnBack1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack1.setText("<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrganizationsWorkRequestHistory)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(btnViewRequestDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnBack1)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblOrganizationsWorkRequestHistory)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnViewRequestDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnBack1)
                .addGap(73, 73, 73))
        );

        tbpRequestHistory.addTab("Request History", jPanel2);

        add(tbpRequestHistory);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed

        int selectedRow = tblPendingWorkRequest.getSelectedRow();

        if (selectedRow >= 0) {
            careTeamLeaderWorkRequest = (CareTeamLeaderWorkRequest) tblPendingWorkRequest.getValueAt(selectedRow, 0);

            NewBookingRequestJPanel nbrjp = new NewBookingRequestJPanel(userProcessContainer, userAccount, organization, enterprise, ecoSystem, careTeamLeaderWorkRequest);
            userProcessContainer.add("New Booking Request JPanel", nbrjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewDetailActionPerformed

    private void btnViewRequestDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestDetailActionPerformed

        int selectedRow = tblWorkRequestHistory.getSelectedRow();

        if (selectedRow >= 0) {
            careTeamLeaderWorkRequest = (CareTeamLeaderWorkRequest) tblPendingWorkRequest.getValueAt(selectedRow, 0);

            OldBookingRequestJPanel obrjp = new OldBookingRequestJPanel(userProcessContainer, careTeamLeaderWorkRequest);
            userProcessContainer.add("Old Booking Request JPanel", obrjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_btnViewRequestDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JButton btnViewRequestDetail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOrganizationsPendingWorkRequest;
    private javax.swing.JLabel lblOrganizationsWorkRequestHistory;
    private javax.swing.JTable tblPendingWorkRequest;
    private javax.swing.JTable tblWorkRequestHistory;
    private javax.swing.JTabbedPane tbpRequestHistory;
    // End of variables declaration//GEN-END:variables
}
