/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.WareHouseEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class CreateWareHouseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateWareHouseJPanel
     */
    private JPanel userProcessContainer;
    private String enterpriseName;
    private EcoSystem ecoSystem;
    private Organization organization;

    public CreateWareHouseJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.organization = organization;

        populateEnterpriseComboBox();
        if (!ecoSystem.getEnterpriseList().isEmpty()) {
            lblMessage.setText("The WareHouse is already created");
            btnCreate.setEnabled(false);
        }
    }

    private void populateEnterpriseComboBox() {
        cmbEnterpriseType.removeAllItems();;

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            if (type.getValue().equals(Enterprise.EnterpriseType.WareHouse.getValue())) {
                cmbEnterpriseType.addItem(type);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        cmbEnterpriseType = new javax.swing.JComboBox();
        lblEnterpriseType = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(102, 204, 255));
        lblMessage.setText("Create WareHouse");

        cmbEnterpriseType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEnterpriseType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnterpriseType.setText("Enterprise Type");

        lblEnterpriseName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnterpriseName.setText("Enterprise Name");

        txtEnterpriseName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnBack)
                .addContainerGap(965, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEnterpriseType)
                            .addComponent(lblEnterpriseName))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEnterpriseType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(421, 421, 421))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(lblMessage)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterpriseType))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnCreate)
                .addGap(75, 75, 75)
                .addComponent(btnBack)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String errorMessage = "";
        int count = 0;

        Enterprise.EnterpriseType enterpriseType = (Enterprise.EnterpriseType) cmbEnterpriseType.getSelectedItem();
        String name = txtEnterpriseName.getText().trim();

        if (enterpriseType == null) {
            count++;
            errorMessage += "Enterprise cannot be Null";
        }
        if (name.isEmpty()) {
            count++;
            errorMessage += "Enterprise Name cannot be Null";
        } else if (!name.matches("[a-zA-Z]+")) {
            count++;
            errorMessage += "Name Should contain only Letters";
        }
        if (count == 0) {

            if (name.equalsIgnoreCase(ecoSystem.getOrganizationName())) {
                count++;
                errorMessage += " An organization with given name already exist, please give a unique name";
            }

            for (Network network : ecoSystem.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise.getOrganizationName().equalsIgnoreCase(name)) {
                        count++;
                        errorMessage += " An organization with given name already exist, please give a unique name";
                        break;
                    }

                    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (org.getOrganizationName().equalsIgnoreCase(name)) {
                            count++;
                            errorMessage += " An organization with given name already exist, please give a unique name";
                            break;
                        }
                    }
                }
            }

            for (Enterprise enterprise : ecoSystem.getEnterpriseList()) {
                if (enterprise.getOrganizationName().equalsIgnoreCase(name)) {
                    count++;
                    errorMessage += "An organization with given name already exist, please give a unique name\n";
                    break;
                }
            }
            
            if (count == 0) {
                if (ecoSystem.getEnterpriseList().isEmpty()) {
                    ecoSystem.createAndAddWareHouseEnterprise(name, enterpriseType);
                    //ecoSystem.getEnterpriseList().add(new WareHouseEnterprise(name, enterpriseType));
                    JOptionPane.showMessageDialog(null, "The WareHouse Enterprise has been created successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Only One WareHouse Enterprise can be created and it has been created already!!!");
                }

            }
        }
        if (count != 0) {
            JOptionPane.showMessageDialog(null, errorMessage);
        }
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cmbEnterpriseType;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtEnterpriseName;
    // End of variables declaration//GEN-END:variables
}
