/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Person.SupplierEnterpriseAdmin;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import UserInterface.SignUpPersonDetailJDialog;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Organization organization;
    private ArrayList<Person> personDirectory;
    private ArrayList<UserAccount> userAccountDirectory;

    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, Organization organization, EcoSystem ecoSystem) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;

        populateNetworkComboBox();
        populateEnterpriseAdminTable();
    }

    private void populateNetworkComboBox() {
        cmbNetwork.removeAllItems();

        for (Network network : ecoSystem.getNetworkList()) {
            cmbNetwork.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        cmbEnterprise.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getPersonDirectory().getPersonList().isEmpty()) {
                cmbEnterprise.addItem(enterprise);
            }
        }
    }

    private void populateRoleComboBox(Enterprise enterprise) {
        cmbRole.removeAllItems();

        for (Role role : enterprise.getSupportedRole()) {
            cmbRole.addItem(role);
        }
    }

    private void populateEnterpriseAdminTable() {

        DefaultTableModel defaultTableModel = (DefaultTableModel) tblEnterpriseAdmin.getModel();
        defaultTableModel.setRowCount(0);

        for (Network network : ecoSystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getOrganizationName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUserName();

                    defaultTableModel.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterpriseAdmin = new javax.swing.JTable();
        lblEnterpriseAdmin = new javax.swing.JLabel();
        lblNewEnterpriseAdmin = new javax.swing.JLabel();
        lblNetwork = new javax.swing.JLabel();
        cmbNetwork = new javax.swing.JComboBox();
        lblEnterprise = new javax.swing.JLabel();
        btnAdminDetail = new javax.swing.JButton();
        cmbEnterprise = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEnterpriseAdmin.setBackground(new java.awt.Color(255, 153, 0));
        tblEnterpriseAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblEnterpriseAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterpriseAdmin);
        if (tblEnterpriseAdmin.getColumnModel().getColumnCount() > 0) {
            tblEnterpriseAdmin.getColumnModel().getColumn(0).setResizable(false);
            tblEnterpriseAdmin.getColumnModel().getColumn(1).setResizable(false);
            tblEnterpriseAdmin.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 760, 91));

        lblEnterpriseAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterpriseAdmin.setForeground(new java.awt.Color(102, 204, 255));
        lblEnterpriseAdmin.setText("Enterprise Admin's");
        add(lblEnterpriseAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        lblNewEnterpriseAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNewEnterpriseAdmin.setForeground(new java.awt.Color(102, 204, 255));
        lblNewEnterpriseAdmin.setText("Create New Enterprise Admin");
        add(lblNewEnterpriseAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        lblNetwork.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNetwork.setText("Network");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        cmbNetwork.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetworkActionPerformed(evt);
            }
        });
        add(cmbNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 250, -1));

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnterprise.setText("Enterprise");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        btnAdminDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdminDetail.setText("Click here to enter Person Details");
        btnAdminDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDetailActionPerformed(evt);
            }
        });
        add(btnAdminDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        cmbEnterprise.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnterpriseActionPerformed(evt);
            }
        });
        add(cmbEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 250, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        cmbRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 250, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDetailActionPerformed
        Enterprise enterprise = (Enterprise) cmbEnterprise.getSelectedItem();

        Role role = (Role) cmbRole.getSelectedItem();
        if (enterprise != null && role != null) {

            personDirectory = enterprise.getPersonDirectory().getPersonList();
            userAccountDirectory = enterprise.getUserAccountDirectory().getUserAccountList();
            organization = enterprise;
            if (organization.getUserAccountDirectory().getUserAccountList().isEmpty()) {
                JFrame frame = new JFrame();
                SignUpPersonDetailJDialog supdjd = new SignUpPersonDetailJDialog(frame, true, organization, ecoSystem, personDirectory, userAccountDirectory);
                supdjd.setVisible(true);
            } else {
                populateEnterpriseAdminTable();
                populateNetworkComboBox();
                if (organization instanceof SupplierEnterprise || organization instanceof HospitalEnterprise) {
                    JOptionPane.showMessageDialog(null, "Admin for this Enterprise is already created");
                } else {
                    JOptionPane.showMessageDialog(null, "Admin for this Organization is already created");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select all combo boxes");
        }
    }//GEN-LAST:event_btnAdminDetailActionPerformed

    private void cmbNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetworkActionPerformed
        cmbEnterprise.removeAllItems();

        Network network = (Network) cmbNetwork.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_cmbNetworkActionPerformed

    private void cmbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnterpriseActionPerformed
        cmbRole.removeAllItems();

        Enterprise enterprise = (Enterprise) cmbEnterprise.getSelectedItem();
        if (enterprise != null) {
            populateRoleComboBox(enterprise);
        }
    }//GEN-LAST:event_cmbEnterpriseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateEnterpriseAdminTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminDetail;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cmbEnterprise;
    private javax.swing.JComboBox cmbNetwork;
    private javax.swing.JComboBox cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseAdmin;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblNewEnterpriseAdmin;
    private javax.swing.JTable tblEnterpriseAdmin;
    // End of variables declaration//GEN-END:variables
}
