/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Network.Network;
import Business.Network.NetworkLocation;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private boolean checkNetworkDuplicate;
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.userProcessContainer = userProcessContainer;

        populateNetworkTable();
        populateLocationComboBox();

    }

    private void populateNetworkTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblNetwork.getModel();
        defaultTableModel.setRowCount(0);
        for (Network network : ecoSystem.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            defaultTableModel.addRow(row);
        }
    }

    private void populateLocationComboBox() {
        cmbLocation.removeAllItems();
        int count = 0;
        for (NetworkLocation.LocationsForNetwork location : NetworkLocation.LocationsForNetwork.values()) {
            for(Network network : ecoSystem.getNetworkList()){
                if(network.getName().equals(location.getValue())){
                    count++;
                    break;
                }
            }
            
            if(count == 0){
                cmbLocation.addItem(location);
            }
            count = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetwork = new javax.swing.JTable();
        lblNetworks = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        cmbLocation = new javax.swing.JComboBox();
        btnCreateNetwork = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblNewNetwork = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNetwork.setBackground(new java.awt.Color(255, 153, 0));
        tblNetwork.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNetwork);
        if (tblNetwork.getColumnModel().getColumnCount() > 0) {
            tblNetwork.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, 91));

        lblNetworks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNetworks.setForeground(new java.awt.Color(102, 204, 255));
        lblNetworks.setText("NETWORKS");
        add(lblNetworks, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLocation.setText("Locations");
        add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        cmbLocation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 270, 140, -1));

        btnCreateNetwork.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreateNetwork.setText("Create Network");
        btnCreateNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNetworkActionPerformed(evt);
            }
        });
        add(btnCreateNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        lblNewNetwork.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNewNetwork.setForeground(new java.awt.Color(102, 204, 255));
        lblNewNetwork.setText("Create New Network");
        add(lblNewNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNetworkActionPerformed
        NetworkLocation.LocationsForNetwork location = (NetworkLocation.LocationsForNetwork) cmbLocation.getSelectedItem();
        checkNetworkDuplicate = false;
        for (Network network : ecoSystem.getNetworkList()) {
            if (location.getValue().equals(network.getName())) {
                checkNetworkDuplicate = true;
                return;
            }
        }
        if(!checkNetworkDuplicate){
            ecoSystem.createAndAddNetwork(location);
            JOptionPane.showMessageDialog(null, "Network has been created successfully");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "The selected Network Already Exist");
        }
        populateLocationComboBox();
        populateNetworkTable();
    }//GEN-LAST:event_btnCreateNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNetwork;
    private javax.swing.JComboBox cmbLocation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblNetworks;
    private javax.swing.JLabel lblNewNetwork;
    private javax.swing.JTable tblNetwork;
    // End of variables declaration//GEN-END:variables
}
