/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import UserInterface.SignUpPersonDetailJDialog;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class ManageWareHouseEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageWareHouseEnterpriseAdminJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Organization organization;
    private ArrayList<Person> personDirectory;
    private ArrayList<UserAccount> userAccountDirectory;

    public ManageWareHouseEnterpriseAdminJPanel(JPanel userProcessContainer, Organization organization, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.ecoSystem = ecoSystem;

        populateEnterpriseComboBox();
    }

    private void populateEnterpriseComboBox() {
        cmbEnterprise.removeAllItems();
        for (Enterprise enterprise : ecoSystem.getEnterpriseList()) {
            for (Person person : enterprise.getPersonDirectory().getPersonList()) {
            }
            if (enterprise.getPersonDirectory().getPersonList().isEmpty()) {
                cmbEnterprise.addItem(enterprise);
            }
        }
    }

    private void populateRoleComboBox(Enterprise enterprise) {
        cmbRole.removeAllItems();

        for (Role role : enterprise.getSupportedRole()) {
            cmbRole.addItem(role);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewEnterpriseAdmin = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbEnterprise = new javax.swing.JComboBox();
        btnAdminDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cmbRole = new javax.swing.JComboBox();

        lblNewEnterpriseAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNewEnterpriseAdmin.setForeground(new java.awt.Color(102, 204, 255));
        lblNewEnterpriseAdmin.setText("Create New WareHouse Enterprise Admin");

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnterprise.setText("Enterprise");

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRole.setText("Role");

        cmbEnterprise.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnterpriseActionPerformed(evt);
            }
        });

        btnAdminDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdminDetail.setText("Click here to enter Admin Details");
        btnAdminDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDetailActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cmbRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewEnterpriseAdmin)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRole)
                                    .addComponent(lblEnterprise))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbEnterprise, 0, 186, Short.MAX_VALUE)
                                    .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(410, 410, 410))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdminDetail)
                        .addGap(449, 449, 449))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(lblNewEnterpriseAdmin)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(cmbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAdminDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDetailActionPerformed
        Enterprise enterprise = (Enterprise) cmbEnterprise.getSelectedItem();
        Role role = (Role) cmbRole.getSelectedItem();

        if (enterprise != null && role != null) {
            personDirectory = enterprise.getPersonDirectory().getPersonList();
            userAccountDirectory = enterprise.getUserAccountDirectory().getUserAccountList();
            organization = enterprise;
            
            if (userAccountDirectory.isEmpty()) {
                JFrame frame = new JFrame();
                SignUpPersonDetailJDialog supdjd = new SignUpPersonDetailJDialog(frame, true, organization, ecoSystem, personDirectory, userAccountDirectory);
                supdjd.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "WareHouse Admin is already created.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select all combo boxes");
        }
    }//GEN-LAST:event_btnAdminDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnterpriseActionPerformed
        cmbRole.removeAllItems();

        Enterprise enterprise = (Enterprise) cmbEnterprise.getSelectedItem();
        if (enterprise != null) {
            populateRoleComboBox(enterprise);
        }
    }//GEN-LAST:event_cmbEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminDetail;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cmbEnterprise;
    private javax.swing.JComboBox cmbRole;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblNewEnterpriseAdmin;
    private javax.swing.JLabel lblRole;
    // End of variables declaration//GEN-END:variables
}
