/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InventorySpecialistWorkArea;

import UserInterface.SupplierWorkArea.*;
import Business.Device;
import com.db4o.foundation.Tree;
import java.awt.CardLayout;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class ViewSelectedDeviceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDeviceDetailJPanel
     */
    private JPanel userProcessContainer;
    private Device device;
    private String deviceName;
    private String deviceType;
    private String deviceStatus;
    private String companyName;
    private double unitPrice;
    private String countryOfOrigin;
    private Date nextMaintainedDate;
    private Date lastMaintainedDate;
    private Date manufacturedDate;
    private int availability;
    private String errorMessage = "";
    private int count = 0;

    public ViewSelectedDeviceJPanel(JPanel userProcessContainer, Device device) {
        initComponents();
        setEditableFalse();
        this.device = device;
        this.userProcessContainer = userProcessContainer;
        txtDeviceName.setText(device.getDeviceName());
        txtUnitPrice.setText(String.valueOf(device.getUnitPrice()));
        txtUniqueDeviceIdentifier.setText(device.getUniqueDeviceIdentifier());
        jDCLastMaintainedDate.setDate(device.getLastMaintainedDate());
        jDCNextMaintainedDate.setDate(device.getNextMaintainedDate());
        txtCompanyName.setText(device.getCompanyName());
        jDCManufacturedDate.setDate(device.getManufacuredDate());
        
        populateDeviceTypeComboBox();
        populateCountryComboBox();
        populateDeviceStatusComboBox();
    }

    private void populateDeviceTypeComboBox() {
        cmbDeviceType.removeAllItems();

        if (cmbDeviceType.isEditable()) {
            cmbDeviceType.addItem(device.getDeviceType());
            for (Device.TypeOfDevice type : Device.TypeOfDevice.values()) {
                if (!type.getType().equals(device.getDeviceType())) {
                    cmbDeviceType.addItem(type);
                }
            }
        } else {
            cmbDeviceType.addItem(device.getDeviceType());
        }
    }

    private void populateDeviceStatusComboBox() {
        cmbDeviceStatus.removeAllItems();

        if (cmbDeviceStatus.isEditable()) {
            cmbDeviceStatus.addItem(device.getDeviceStatus());
            for (Device.DeviceStatus status : Device.DeviceStatus.values()) {
                if (!status.getStatus().equals(device.getDeviceStatus())) {
                    cmbDeviceStatus.addItem(status);
                }
            }
        } else {
            cmbDeviceStatus.addItem(device.getDeviceStatus());
        }
    }

    private void populateCountryComboBox() {
        cmbCountryOfOrigin.removeAllItems();

        if (cmbCountryOfOrigin.isEditable()) {
            String[] countries = Locale.getISOCountries();
            cmbCountryOfOrigin.addItem(device.getCountryOfOrigin());

            for (String countryCode : countries) {
                Locale locale = new Locale("", countryCode);
                if (!device.getCountryOfOrigin().equals(locale.getDisplayCountry())) {
                    cmbCountryOfOrigin.addItem(locale.getDisplayCountry());
                }
            }
        } else {
            cmbCountryOfOrigin.addItem(device.getCountryOfOrigin());
        }
    }

    private void setEditableFalse() {
        txtDeviceName.setEditable(false);
        cmbDeviceStatus.setEditable(false);
        cmbDeviceType.setEditable(false);
        txtUnitPrice.setEditable(false);
        jDCLastMaintainedDate.setEnabled(false);
        jDCNextMaintainedDate.setEnabled(false);
        jDCManufacturedDate.setEnabled(false);
        txtCompanyName.setEditable(false);
        cmbCountryOfOrigin.setEditable(false);
    }

//    private void setEditableTrue() {
//        txtDeviceName.setEditable(true);
//        cmbDeviceStatus.setEditable(true);
//        cmbDeviceType.setEditable(true);
//        txtUnitPrice.setEditable(true);
//        jDCLastMaintainedDate.setEnabled(true);
//        jDCNextMaintainedDate.setEnabled(true);
//        jDCManufacturedDate.setEnabled(true);
//        txtCompanyName.setEditable(true);
//        cmbCountryOfOrigin.setEditable(true);
//        btnSave.setEnabled(true);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageProductCatalog1 = new javax.swing.JLabel();
        lblDeviceName = new javax.swing.JLabel();
        txtDeviceName = new javax.swing.JTextField();
        lblUniqueDeviceIdentifier = new javax.swing.JLabel();
        lblCompanyName = new javax.swing.JLabel();
        lblNextMaintainedDate = new javax.swing.JLabel();
        lblLastMaintainedDate = new javax.swing.JLabel();
        lblDeviceStatus = new javax.swing.JLabel();
        lblDeviceType = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        lblCountryOfOrigin = new javax.swing.JLabel();
        lblManufacturedDate = new javax.swing.JLabel();
        txtUniqueDeviceIdentifier = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        cmbDeviceType = new javax.swing.JComboBox();
        cmbCountryOfOrigin = new javax.swing.JComboBox();
        jDCLastMaintainedDate = new com.toedter.calendar.JDateChooser();
        jDCNextMaintainedDate = new com.toedter.calendar.JDateChooser();
        cmbDeviceStatus = new javax.swing.JComboBox();
        jDCManufacturedDate = new com.toedter.calendar.JDateChooser();

        lblManageProductCatalog1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageProductCatalog1.setForeground(new java.awt.Color(102, 204, 255));
        lblManageProductCatalog1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageProductCatalog1.setText("Device Detail");

        lblDeviceName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDeviceName.setText("Device Name");

        txtDeviceName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblUniqueDeviceIdentifier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUniqueDeviceIdentifier.setText("Unique Device Identifier");

        lblCompanyName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompanyName.setText("Company Name");

        lblNextMaintainedDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNextMaintainedDate.setText("Next Maintained Date");

        lblLastMaintainedDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLastMaintainedDate.setText("Last Maintained Date");

        lblDeviceStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDeviceStatus.setText("Device Status");

        lblDeviceType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDeviceType.setText("Device Type");

        lblUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUnitPrice.setText("Unit Price");

        lblCountryOfOrigin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCountryOfOrigin.setText("Country Of Origin");

        lblManufacturedDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblManufacturedDate.setText("Manufactured Date");

        txtUniqueDeviceIdentifier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtCompanyName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cmbDeviceType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbDeviceType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCountryOfOrigin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCountryOfOrigin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDeviceStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbDeviceStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblDeviceName)
                        .addGap(18, 18, 18)
                        .addComponent(txtDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUniqueDeviceIdentifier)
                            .addComponent(lblCompanyName)
                            .addComponent(lblLastMaintainedDate)
                            .addComponent(lblNextMaintainedDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUniqueDeviceIdentifier)
                                .addComponent(txtCompanyName)
                                .addComponent(jDCLastMaintainedDate, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(jDCNextMaintainedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCountryOfOrigin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManufacturedDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeviceStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeviceType, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbDeviceStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbCountryOfOrigin, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDCManufacturedDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(cmbDeviceType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManageProductCatalog1)
                .addGap(431, 431, 431))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(lblManageProductCatalog1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDCLastMaintainedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbDeviceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDeviceType)
                                    .addComponent(lblDeviceName)
                                    .addComponent(txtDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbDeviceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDeviceStatus)
                                    .addComponent(txtUniqueDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUniqueDeviceIdentifier))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnitPrice)
                                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCompanyName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbCountryOfOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCountryOfOrigin))
                                    .addComponent(lblLastMaintainedDate, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDCManufacturedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManufacturedDate)
                            .addComponent(jDCNextMaintainedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNextMaintainedDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(65, 65, 65)
                .addComponent(btnBack)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cmbCountryOfOrigin;
    private javax.swing.JComboBox cmbDeviceStatus;
    private javax.swing.JComboBox cmbDeviceType;
    private com.toedter.calendar.JDateChooser jDCLastMaintainedDate;
    private com.toedter.calendar.JDateChooser jDCManufacturedDate;
    private com.toedter.calendar.JDateChooser jDCNextMaintainedDate;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblCountryOfOrigin;
    private javax.swing.JLabel lblDeviceName;
    private javax.swing.JLabel lblDeviceStatus;
    private javax.swing.JLabel lblDeviceType;
    private javax.swing.JLabel lblLastMaintainedDate;
    private javax.swing.JLabel lblManageProductCatalog1;
    private javax.swing.JLabel lblManufacturedDate;
    private javax.swing.JLabel lblNextMaintainedDate;
    private javax.swing.JLabel lblUniqueDeviceIdentifier;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtDeviceName;
    private javax.swing.JTextField txtUniqueDeviceIdentifier;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
