/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.HospitalEnterpriseAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Room;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Collection;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class HospitalEnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    
    public HospitalEnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplierAdminWorkArea = new javax.swing.JLabel();
        btnManageOrganization = new javax.swing.JButton();
        btnManageOrganizationAdmin = new javax.swing.JButton();
        btnManageRooms = new javax.swing.JButton();

        lblSupplierAdminWorkArea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSupplierAdminWorkArea.setForeground(new java.awt.Color(102, 204, 255));
        lblSupplierAdminWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplierAdminWorkArea.setText("Hospital Enterprise Admin Work Area");

        btnManageOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageOrganization.setText("Manage Organization");
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });

        btnManageOrganizationAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageOrganizationAdmin.setText("Manage Organization Admin");
        btnManageOrganizationAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationAdminActionPerformed(evt);
            }
        });

        btnManageRooms.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageRooms.setText("Manage Rooms");
        btnManageRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRoomsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierAdminWorkArea)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageOrganizationAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblSupplierAdminWorkArea)
                .addGap(72, 72, 72)
                .addComponent(btnManageOrganization)
                .addGap(54, 54, 54)
                .addComponent(btnManageOrganizationAdmin)
                .addGap(55, 55, 55)
                .addComponent(btnManageRooms)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed
        ManageHOrganizationJPanel mhojp = new ManageHOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("Manage H Organization JPanel",mhojp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrganizationActionPerformed

    private void btnManageOrganizationAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationAdminActionPerformed
        ManageHOrganizationAdminJPanel mhoajp = new ManageHOrganizationAdminJPanel(userProcessContainer, userAccount, enterprise, EcoSystem.ecoSystem);
        userProcessContainer.add("Manage H Organization Admin JPanel",mhoajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrganizationAdminActionPerformed

    private void btnManageRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRoomsActionPerformed
        ManageRoomsJPanel mrjp = new ManageRoomsJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("Manage Rooms JPanel",mrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRoomsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnManageOrganizationAdmin;
    private javax.swing.JButton btnManageRooms;
    private javax.swing.JLabel lblSupplierAdminWorkArea;
    // End of variables declaration//GEN-END:variables
}
