/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalEnterpriseAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.CareTeamSpecialistRole;
import Business.Role.Role;
import Business.Role.StaffRole;
import Business.UserAccount.UserAccount;
import UserInterface.SignUpPersonDetailJDialog;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class ManageHOrganizationAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationAdminJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private Organization organization;
    private ArrayList<Person> personDirectory;
    private ArrayList<UserAccount> userAccountDirectory;

    public ManageHOrganizationAdminJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        
        populateOrganizationAdminTable();
        populateOrganizationComboBox();
    }

    private void populateOrganizationAdminTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblOrganizationAdmin.getModel();
        defaultTableModel.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountList()) {
                Object[] row = new Object[4];
                row[0] = enterprise.getOrganizationName();
                row[1] = organization.getOrganizationName();
                row[2] = userAccount.getRole();
                row[3] = userAccount.getUserName();

                defaultTableModel.addRow(row);
            }
        }
    }

    private void populateOrganizationComboBox() {
        cmbOrganization.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            cmbOrganization.addItem(organization);
        }
    }

    private void populateRoleComboBox(Organization organization) {
        cmbRole.removeAllItems();

        for (Role role : organization.getSupportedRole()) {
            cmbRole.addItem(role);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrganizationAdmin = new javax.swing.JLabel();
        lblNewOrganizationPerson = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizationAdmin = new javax.swing.JTable();
        cmbRole = new javax.swing.JComboBox();
        lblRole = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblOrganization = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox();
        btnPersonDetail = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        lblOrganizationAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrganizationAdmin.setForeground(new java.awt.Color(102, 204, 255));
        lblOrganizationAdmin.setText("Organization Admin's");

        lblNewOrganizationPerson.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNewOrganizationPerson.setForeground(new java.awt.Color(102, 204, 255));
        lblNewOrganizationPerson.setText("Create New Organization Person");

        tblOrganizationAdmin.setBackground(new java.awt.Color(255, 153, 0));
        tblOrganizationAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblOrganizationAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Organization Name", "Role", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganizationAdmin);

        cmbRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRole.setText("Role");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrganization.setText("Organization");

        cmbOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationActionPerformed(evt);
            }
        });

        btnPersonDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPersonDetail.setText("Click here to enter Person Details");
        btnPersonDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonDetailActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRefresh)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblOrganizationAdmin)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrganization)
                            .addComponent(lblRole))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbOrganization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblNewOrganizationPerson)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnPersonDetail)))
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganizationAdmin)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblNewOrganizationPerson)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPersonDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
        cmbRole.removeAllItems();

        Organization organization = (Organization) cmbOrganization.getSelectedItem();
        if (organization != null) {
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_cmbOrganizationActionPerformed

    private void btnPersonDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonDetailActionPerformed
        Organization organization = (Organization) cmbOrganization.getSelectedItem();
        personDirectory = organization.getPersonDirectory().getPersonList();
        userAccountDirectory = organization.getUserAccountDirectory().getUserAccountList();
        //organization = enterprise;
        Role role = (Role) cmbRole.getSelectedItem();
        if (organization != null || role != null) {
            JFrame frame = new JFrame();
            
            if(role instanceof StaffRole){
                SignUpStaffPersonDetailJDialog suspdjd = new SignUpStaffPersonDetailJDialog(frame, true, organization, ecoSystem, personDirectory, role);
                suspdjd.setVisible(true);
            }
            else{
                SignUpPersonDetailJDialog supdjd = new SignUpPersonDetailJDialog(frame, true, organization, ecoSystem, personDirectory, userAccountDirectory);
                supdjd.setVisible(true);
            }
//            if (role instanceof CareTeamSpecialistRole) {
//                
//                SignUpPersonDetailJDialog supdjd = new SignUpPersonDetailJDialog(frame, true, organization, ecoSystem, personDirectory, userAccountDirectory);
//                supdjd.setVisible(true);
//            }
//            else if(role instanceof StaffRole){
//                SignUpStaffPersonDetailJDialog suspdjd = new SignUpStaffPersonDetailJDialog(frame, true, organization, ecoSystem, personDirectory, role);
//                suspdjd.setVisible(true);
//            }
            
        }
    }//GEN-LAST:event_btnPersonDetailActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateOrganizationAdminTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPersonDetail;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cmbOrganization;
    private javax.swing.JComboBox cmbRole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNewOrganizationPerson;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblOrganizationAdmin;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTable tblOrganizationAdmin;
    // End of variables declaration//GEN-END:variables
}
