/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalEnterpriseAdminWorkArea;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Room;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tushar
 */
public class ManageRoomsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRoomsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private String errorMessage;
    private int roomNumber;
    private int floorNumber;
    private int count = 0;

    public ManageRoomsJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblManageRooms = new javax.swing.JLabel();
        txtRoomNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFloorNumber = new javax.swing.JTextField();
        btnAddRoom = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Room Number");

        lblManageRooms.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageRooms.setForeground(new java.awt.Color(102, 204, 255));
        lblManageRooms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageRooms.setText("Manage Rooms");

        txtRoomNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Floor Number");

        txtFloorNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnAddRoom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddRoom.setText("Add Room");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(407, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblManageRooms)
                        .addGap(409, 409, 409))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btnAddRoom))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRoomNumber)
                                    .addComponent(txtFloorNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(363, 363, 363))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblManageRooms)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtFloorNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAddRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed

        errorMessage = "";
        count = 0;

        if (txtFloorNumber.getText().trim().isEmpty() || txtRoomNumber.getText().trim().isEmpty()) {
            errorMessage += "You have left the below mentioned field as blank, Please fill them.\n";

            if (txtFloorNumber.getText().trim().isEmpty()) {
                count++;
                errorMessage += count + ". Floor Number\n";
            }
            if (txtRoomNumber.getText().trim().isEmpty()) {
                count++;
                errorMessage += count + ". Room Number\n";
            }
        }

        if (count == 0) {

            try {
                roomNumber = Integer.parseInt(txtRoomNumber.getText().trim());
            } catch (NumberFormatException numberFormatException) {
                count++;
                errorMessage += "Invalid Room Number, Please enter integer value\n";
            }
            try {
                floorNumber += Integer.parseInt(txtFloorNumber.getText().trim());
            } catch (NumberFormatException numberFormatException) {
                count++;
                errorMessage += "Invalid Floor Number, Please enter integer value\n";
            }
        }

        if (count == 0) {
            HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) enterprise;

            for (Room room : hospitalEnterprise.getRoomDirectory().getRoomList()) {
                if (room.getRoomNumber() == roomNumber) {
                    count++;
                }
            }
            if (count == 0) {
                Room room = hospitalEnterprise.getRoomDirectory().addRoom(roomNumber, floorNumber);

                if (room != null) {
                    JOptionPane.showMessageDialog(null, "Room has been added successfully\n");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, roomNumber + " room already exist\n");
            }
        } else {
            JOptionPane.showMessageDialog(null, errorMessage);
        }

    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblManageRooms;
    private javax.swing.JTextField txtFloorNumber;
    private javax.swing.JTextField txtRoomNumber;
    // End of variables declaration//GEN-END:variables
}
